import type { Project, UomSet } from '@/types'

/** Default unit set used by the sample project and as the app default. */
export const DEFAULT_UOM: UomSet = {
  mass: 'kg',
  volume: 'L',
  temperature: 'C',
  time: 'min',
  pressure: 'kPa',
  energy: 'kJ',
}

/**
 * "Aspirin Synthesis" — a small but complete sample project that gives every UI prompt real data
 * to render: one BpProcess, one "R&D Scale" Step, four unit procedures, plus the materials,
 * reaction set and equipment they reference.
 */
export const ASPIRIN_SAMPLE: Project = {
  id: 'proj-aspirin',
  name: 'Aspirin Synthesis',
  description: 'Acetylation of salicylic acid with acetic anhydride to produce aspirin.',
  company: 'OpenBatch Demo Co.',
  author: 'OpenBatch',
  createdAt: '2026-01-01T00:00:00.000Z',
  modifiedAt: '2026-01-01T00:00:00.000Z',
  uom: DEFAULT_UOM,
  utilities: [
    { id: 'util-cw', name: 'Cooling Water', type: 'Cooling', supplyTemperature: 7, returnTemperature: 12 },
    { id: 'util-steam', name: 'Steam', type: 'Heating', supplyTemperature: 150 },
  ],
  materials: [
    {
      id: 'mat-salicylic',
      name: 'SALICYLIC-ACID',
      aliases: ['SA', 'Salicylic Acid', '2-Hydroxybenzoic acid'],
      type: 'PureComponent',
      defaultPhase: 'Solid',
      molecularWeight: 138.12,
      density: 1443,
      meltingPoint: 158,
      formula: 'C7H6O3',
      notes: '',
    },
    {
      id: 'mat-acetic-anhydride',
      name: 'ACETIC-ANHYDRIDE',
      aliases: ['AAN', 'Acetic Anhydride'],
      type: 'PureComponent',
      defaultPhase: 'Liquid',
      molecularWeight: 102.09,
      density: 1080,
      boilingPoint: 139.8,
      formula: 'C4H6O3',
      notes: '',
    },
    {
      id: 'mat-aspirin',
      name: 'ASPIRIN',
      aliases: ['ASA', 'Acetylsalicylic Acid'],
      type: 'PureComponent',
      defaultPhase: 'Solid',
      molecularWeight: 180.16,
      density: 1400,
      meltingPoint: 135,
      formula: 'C9H8O4',
      notes: '',
    },
    {
      id: 'mat-acetic-acid',
      name: 'ACETIC-ACID',
      aliases: ['AcOH', 'Acetic Acid'],
      type: 'PureComponent',
      defaultPhase: 'Liquid',
      molecularWeight: 60.05,
      density: 1049,
      boilingPoint: 118,
      formula: 'C2H4O2',
      notes: '',
    },
    {
      id: 'mat-water',
      name: 'WATER',
      aliases: ['H2O', 'Water'],
      type: 'PureComponent',
      defaultPhase: 'Liquid',
      molecularWeight: 18.02,
      density: 997,
      boilingPoint: 100,
      meltingPoint: 0,
      heatCapacityLiquid: 4186,
      heatOfVaporization: 2_257_000,
      antoineA: 8.07131,
      antoineB: 1730.63,
      antoineC: 233.426,
      formula: 'H2O',
      notes: '',
    },
  ],
  reactions: [
    {
      id: 'rxn-aspirin',
      name: 'Aspirin Synthesis',
      description: 'Salicylic acid + acetic anhydride -> aspirin + acetic acid.',
      reactions: [
        {
          id: 'rxn-aspirin-1',
          name: 'Acetylation',
          reactants: [
            { materialId: 'mat-salicylic', stoichiometricCoeff: 1, phase: 'Solid' },
            { materialId: 'mat-acetic-anhydride', stoichiometricCoeff: 1, phase: 'Liquid' },
          ],
          products: [
            { materialId: 'mat-aspirin', stoichiometricCoeff: 1, phase: 'Solid' },
            { materialId: 'mat-acetic-acid', stoichiometricCoeff: 1, phase: 'Liquid' },
          ],
          keyComponentId: 'mat-salicylic',
          conversionPct: 95,
          heatOfReaction: -50000,
          reactionType: 'Stoichiometric',
        },
      ],
    },
  ],
  facilities: [
    {
      id: 'fac-1',
      name: 'Pilot Plant',
      location: 'Building 1',
      notes: '',
      equipmentUnits: [
        {
          id: 'eq-reactor1',
          name: 'Reactor-1',
          tag: 'R-101',
          equipmentClass: 'Reactor',
          totalVolume: 1.0,
          workingVolumeFraction: 0.8,
          materialOfConstruction: '316L SS',
          utilities: [],
          notes: '',
        },
        {
          id: 'eq-cryst1',
          name: 'Crystallize-1',
          tag: 'CR-101',
          equipmentClass: 'Crystallizer',
          totalVolume: 1.0,
          workingVolumeFraction: 0.8,
          materialOfConstruction: '316L SS',
          utilities: [],
          notes: '',
        },
        {
          id: 'eq-filter1',
          name: 'Filter-1',
          tag: 'F-101',
          equipmentClass: 'Filter',
          totalVolume: 0.5,
          workingVolumeFraction: 0.8,
          materialOfConstruction: '316L SS',
          utilities: [],
          notes: '',
        },
        {
          id: 'eq-dryer1',
          name: 'Dryer-1',
          tag: 'D-101',
          equipmentClass: 'Dryer',
          totalVolume: 0.5,
          workingVolumeFraction: 0.8,
          materialOfConstruction: '316L SS',
          utilities: [],
          notes: '',
        },
      ],
    },
  ],
  processes: [
    {
      id: 'proc-1',
      name: 'Aspirin Synthesis',
      description: 'Batch synthesis of aspirin.',
      keyProduct: 'mat-aspirin',
      steps: [
        {
          id: 'step-1',
          name: 'R&D Scale',
          description: 'Lab-scale batch.',
          facilityId: 'fac-1',
          uom: DEFAULT_UOM,
          unitProcedures: [
            {
              id: 'up-reaction',
              name: 'Reaction',
              primaryEquipmentId: 'eq-reactor1',
              operations: [
                {
                  id: 'op-charge-sa',
                  type: 'Charge',
                  displayName: 'Charge SALICYLIC-ACID',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-reactor1',
                  materials: [{ materialId: 'mat-salicylic', amount: 100, amountUnit: 'kg' }],
                  chargeTimeMin: 15,
                },
                {
                  id: 'op-charge-aan',
                  type: 'Charge',
                  displayName: 'Charge ACETIC-ANHYDRIDE',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-reactor1',
                  materials: [
                    { materialId: 'mat-acetic-anhydride', amount: 80, amountUnit: 'kg' },
                  ],
                  chargeTimeMin: 10,
                },
                {
                  id: 'op-react',
                  type: 'React',
                  displayName: 'React',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-reactor1',
                  reactionDataSetId: 'rxn-aspirin',
                  reactionTimeMin: 60,
                  temperatureC: 90,
                },
              ],
            },
            {
              id: 'up-cryst',
              name: 'Crystallization',
              primaryEquipmentId: 'eq-cryst1',
              operations: [
                {
                  id: 'op-cool',
                  type: 'Cool',
                  displayName: 'Cool',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-cryst1',
                  targetTemperatureC: 5,
                  coolingTimeMin: 45,
                },
                {
                  id: 'op-crystallize',
                  type: 'Crystallize',
                  displayName: 'Crystallize',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-cryst1',
                  productMaterialId: 'mat-aspirin',
                  crystallizationTimeMin: 60,
                  finalTemperatureC: 5,
                  separation: { solidFraction: 0.9 },
                },
              ],
            },
            {
              id: 'up-filt',
              name: 'Filtration',
              primaryEquipmentId: 'eq-filter1',
              operations: [
                {
                  id: 'op-filter',
                  type: 'Filter',
                  displayName: 'Filter',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-filter1',
                  filtrationTimeMin: 30,
                  cakeSolidFraction: 0.6,
                },
                {
                  id: 'op-wash',
                  type: 'WashCake',
                  displayName: 'Wash Cake',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-filter1',
                  washMaterialId: 'mat-water',
                  washAmount: 20,
                  washAmountUnit: 'kg',
                  numberOfWashes: 2,
                },
              ],
            },
            {
              id: 'up-dry',
              name: 'Drying',
              primaryEquipmentId: 'eq-dryer1',
              operations: [
                {
                  id: 'op-dry',
                  type: 'Dry',
                  displayName: 'Dry',
                  isEnabled: true,
                  notes: '',
                  startAfterConstraints: [],
                  equipmentId: 'eq-dryer1',
                  dryingTimeMin: 120,
                  finalMoistureFraction: 0.005,
                  temperatureC: 50,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  productionPlans: [
    {
      id: 'plan-1',
      name: 'Q1 Campaign',
      description: 'Demonstration production plan.',
      entries: [{ id: 'ple-1', processId: 'proc-1', stepId: 'step-1', numberOfBatches: 5 }],
    },
  ],
}
